### ISSUE TITLE
USER STORY: Display dietary category menu items

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#10]
### Epic:
- [x] #8  

### Description:
As a user, I can see the Keto, Vegan or Gluten-Free dietary types in the navbar, so that I can quickly access the chocolates I am interested in .

### Acceptance Criteria:
- [x] Dietary types are displayed prominently in the navbar

### Tasks:
- [x] Add dietary types to navbar
- [x] Update view to return relevant results

### Story Points:
1
