### ISSUE TITLE
USER STORY: Register for account

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#14]
### Epic:
- [x] #12 

### Description:
As a user, I can easily and quickly register for an account, so that I can create a profile, leave chocolate reviews and have access to my order history.

### Acceptance Criteria:
- [x] User can register for an account by completing the necessary Allauth verification steps

### Tasks:
- [x] Set up Allauth
- [x] Set up necessary templates

### Story Points:
1
