### ISSUE TITLE
USER STORY: As a user I can easily log in and log out

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#15]
### Epic:
#12 

### Description:
As a user, I can easily log in and log out of the site, so that I can use the site effectively.

### Acceptance Criteria:
- [x] User can log in
- [x] User can log out
- [x] User is presented with their log in status in the 'My Account' drop down menu

### Tasks:
- [x] Set up templates with necessary links
- [x] Set up Allauth templates

### Story Points:
1
