### ISSUE TITLE
USER STORY: Retrieve forgotten password

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#16]
### Epic:
#12 

### Description:
As a user, I can retrieve my password in the event that it is forgotten, so that I can access the site.

### Acceptance Criteria:
- [x] User can reset their password

### Tasks:
- [x] Set up email configuration
- [x] Set up Allauth templates

### Story Points:
1
