### ISSUE TITLE
USER STORY: Allow user to create profile

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#18]
### Epic:
#12 

### Description:
As a user, I can create a personal user profile, so that I can save default delivery information, leave chocolate reviews, view my order history.

### Acceptance Criteria:
- [x] User can create a user profile

### Tasks:
- [x] Create profile app
- [x] Set up models
- [x] Set up templates
- [x] Set up views

### Story Points:
1
