### ISSUE TITLE
USER STORY: Sort Chocolates on main menu page

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#20]
### Epic:
#19 

### Description:
As a user, I can sort the chocolates on the main menu page, so that I can see navigate the chocolate menu and see the chocolates from lowest price to highest etc.

### Acceptance Criteria:
- [x] User can select which sorting method they wish to use on the main chocolates menu page

### Tasks:
- [x] Set up views in chocolates app
- [x] Set up sorting dropdown menu in template

### Story Points:
2
