### ISSUE TITLE
USER STORY: Search for chocolate using name or description

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#22]
### Epic:
#19 

### Description:
As a user, I can use the search form to search for a chocolate, so that I can make a selection to purchase.

### Acceptance Criteria:
- [x] User can use the search form to search site
- [ ] Search results are displayed to user

### Tasks:
- [x] Set up view to accept search query

### Story Points:
3
