### ISSUE TITLE
USER STORY: Display search results

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#23]
### Epic:
#19 

### Description:
As a user, I can see the results of my search, so that I can browse the returned results.

### Acceptance Criteria:
- [x] Search results are displayed to user
- [x] Number of search results are displayed to user

### Tasks:
- [x] Set up view to return results in context
- [x] Set up template to display results and number of results

### Story Points:
3
