### ISSUE TITLE
USER STORY: Add chocolate

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#31]
### Epic:
#30 

### Description:
As a superuser, I can add a chocolate, so that the chocolate selection can be managed.

### Acceptance Criteria:
- [x] Superuser can add a chocolate to the site

### Tasks:
- [x] Set up chocolate management template
- [x] Set up chocolate management form
- [x] Set up views

### Story Points:
4
