### ISSUE TITLE
USER STORY: Edit chocolate details

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#32]
### Epic:
#30 

### Description:
As a superuser, I can edit the chocolate details directly from site, so that I can make amendments quickly to the chocolates on the site.

### Acceptance Criteria:
- [x] Superuser can successfully edit the chocolate from the site

### Tasks:
- [x] Set up edit chocolate template, form, view and url
- [x] Set up edit button in chocolates main menu and chocolate details page

### Story Points:
3
