### ISSUE TITLE
USER STORY: Chocolate review

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#36]
### Epic:
#34 

### Description:
As a user, I can leave a review in the textfield in the review section of the chocolate detail page, so that I can let other customers know my perception of the quality.

### Acceptance Criteria:
- [x] User can leave a text review successfully
- [x] Toast error message is displayed if the textfield is blank when the submit button is clicked

### Tasks:
- [x] Create textfield in the review section of the chocolate detail page
- [x] Add validation in view to trigger error message if the review is blank when submitted

### Story Points:
3
