### ISSUE TITLE
USER STORY:  This is a test for the milestone label

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#7]
### Description:
As a role, I can function, so that result.

### Acceptance Criteria:
- [x] This is a test
- [ ] This is another test

### Tasks:
- [x] This is a test
- [ ] This is another test
