### ISSUE TITLE
USER STORY: Display individual chocolate details

### ISSUE THREAD

**Issue by DannyGilligan** [DannyGilligan/chocelegance-project#9]
### Epic:
- [x] #8 

### Description:
As a role user, I can view the details of an individual chocolate, so that I can decide whether to purchase or not.

### Acceptance Criteria:
- [x] Individual chocolate details are presented to user

### Tasks:
- [x] Set up template, view and url pattern to render the page to the user
- [x] Populate Chocolate model with relevant values

### Story Points:
1
